# Generated by Django 2.1.1 on 2018-09-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название услуги')),
                ('short_desc', models.CharField(blank=True, max_length=128, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, upload_to='products/products_images')),
            ],
        ),
    ]
