# Generated by Django 2.1.1 on 2018-09-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='charact',
            field=models.TextField(blank=True, verbose_name='Характеристики товара'),
        ),
    ]
