# Generated by Django 2.1.1 on 2018-09-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название примера работ')),
                ('image', models.ImageField(blank=True, upload_to='portfolio_images')),
                ('description', models.TextField(blank=True, verbose_name='описание примера работ')),
            ],
        ),
    ]
