# Generated by Django 2.1.1 on 2018-09-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioexample',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/portfolio_images'),
        ),
    ]
